name: Call Reusable Workflow

#on: [push]
on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: surendba/githook-test/.github/workflows/main.yml@master
    with:
      greeting: "Hello from another repo!"
